[package]
name = "peasy"
version = "0.1.0"
authors = ["Tyler Mandry <tmandry@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gen_macro = { path = "./gen_macro" }

clang = { version = "0.23.0", features = ["clang_8_0"] }
thiserror = "1.0.9"
codespan = { git = "https://github.com/tmandry/codespan.git", branch = "diagnostic-eq" }
codespan-reporting = { git = "https://github.com/tmandry/codespan.git", branch = "diagnostic-eq" }
termcolor = "1.1.0"
lazy_static = "1.4.0"
salsa = "0.14.1"
rental = "0.5.4"
itertools = "0.9"

[dev-dependencies]
pretty_assertions = "0.6.1"
