[package]
name = "gen_macro"
version = "0.1.0"
authors = ["Tyler Mandry <tmandry@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gen_macro_impl = { path = "./impl" }
proc-macro-hack = "0.5"
